### PR TITLE
Dockerize this repository for local development

### PR DESCRIPTION
**Pull request by Sammidysam**
Trello: https://trello.com/c/WIxmczPW/99-set-up-environmentaldashboardorg-docker-development-for-oliver

This pull request provides our usual pattern of files for running a Docker environment, a `Dockerfile`, `build.sh` and `run.sh`, so that this can be developed locally more easily.

@oliverripps can you try the instructions in the README?  The server will run on port 3003.  This will allow you to develop without the weird hacky way that I showed you.

@Terf Are you okay with this using the PHP Docker image so that less code is needed?  I really like the clean 5-line Dockerfile.

### CODE REVIEW

**Comment by Terf** [comment]
Yeah, that'd be great

**Comment by Sammidysam** [comment]
Awesome, let me know if you have any other comments for this setup.

**Comment by Sammidysam** [comment]
@oliverripps Pinging this for testing since it has been 4 weeks.

**Comment by Sammidysam** [comment]
Aw, it makes me so happy that this got reviewed and merged!

**Pull request merged**
